### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by DestinyPegasus999** [crllect/Bunker-v6-Proxy-And-Browsers123124#1]
It's been like this for a while?

Here's what I get:

This Deployment has been disabled.

Your connection is working correctly.

Vercel is working correctly.

402: PAYMENT_REQUIRED
Code: DEPLOYMENT_DISABLED
ID: iad1::t7ll8-1724968279810-6717cb805f71

**Comment by DestinyPegasus999** [comment]
> It's been like this for a while?
> 
> Here's what I get:
> 
> This Deployment has been disabled.
> 
> Your connection is working correctly.
> 
> Vercel is working correctly.
> 
> 402: PAYMENT_REQUIRED Code: DEPLOYMENT_DISABLED ID: iad1::t7ll8-1724968279810-6717cb805f71

https://vercel.com/docs/errors/DEPLOYMENT_DISABLED

**Comment by crllect** [comment]
Hey yea this repo isnt my project. Its a fork of https://github.com/Brandon421-ops/Bunker-v6-Proxy-And-Browser which I presume has been shut-down or privated. The error means the maintainer hasnt paid for their vercel server. Sorry abt that
